#!/usr/bin/env bash

root=".."

NAME=protobuf-c
VERSION=1.2.1
URL="https://github.com/protobuf-c/protobuf-c/releases/download/v$VERSION/protobuf-c-$VERSION.tar.gz"

run_configure () {
    ./configure --host=$1 --disable-protoc --prefix=/usr
}

source "$(dirname $0)/$root/build"
