#!/usr/bin/env bash

root=".."

NAME=protobuf-c
VERSION=0.14
URL="https://protobuf-c.googlecode.com/files/$NAME-$VERSION.tar.gz"

run_configure () {
    ./configure --host=$1 --disable-protoc --prefix=/usr
}

source "$(dirname $0)/$root/build"
