#!/usr/bin/env bash
set -e

cd $(dirname $0)
rm -rf "toolchain"

for l in openssl c-ares curl libdaemon libmicrohttpd libxml2 ; do
    [ -x "$l/build" ] || {
	echo "ERROR: Cannot execute $l/build." >&2
	exit 1;
    }
    $l/build
done

