#!/usr/bin/env bash

root=".."

NAME=lua
VERSION=5.2.3
URL="http://www.lua.org/ftp/$NAME-$VERSION.tar.gz"

run_configure () {
    return;
}

run_build () {
    make posix DESTDIR="$1"
}



source "$(dirname $0)/$root/build"
