#!/usr/bin/env bash

root=".."

NAME=libxml2
VERSION=2.9.0
URL="ftp://xmlsoft.org/libxml2/$NAME-$VERSION.tar.gz"

run_configure () {
    run_autoreconf
    ./configure --host=$1 --prefix=/usr --without-python
}

source "$(dirname $0)/$root/build"
