#!/usr/bin/env bash

root=".."

NAME=openssl
VERSION=1.0.2k
URL="http://www.openssl.org/source/$NAME-$VERSION.tar.gz"

run_configure () {
    unset CC
    CROSS_COMPILE=$1- INSTALL_PREFIX="$sysroot" \
	./Configure --prefix=/usr/ android
}

source "$(dirname $0)/$root/build"
