#!/usr/bin/env bash

root=".."

NAME=db
VERSION=5.1.29
URL="http://download.oracle.com/berkeley-db/$NAME-$VERSION.tar.gz"

run_configure () {
    ./dist/configure --host=$1 --prefix=/usr \
        --enable-smallbuild \
        --enable-debug \
        --disable-hash \
        --disable-mutexsupport \
        --disable-partition \
        --disable-replication \
        --disable-statistics
}

source "$(dirname $0)/$root/build"
