#!/usr/bin/env bash

root=".."

NAME=curl
VERSION=7.53.1
URL="http://curl.haxx.se/download/$NAME-$VERSION.tar.gz"

DEPENDS="c-ares/1.12.0/libcares"

run_configure () {
    run_autoreconf
    LIBS=-lcares ./configure --host=$1 --prefix=/usr --enable-ares
}

source "$(dirname $0)/$root/build"
